# Generated by Django 5.0.6 on 2024-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converted/%Y/%m/%d')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
